package sqlite

var schemaStatements = []string{
	`CREATE TABLE IF NOT EXISTS conversations (
		id TEXT PRIMARY KEY,
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS content_objects (
		object_id TEXT NOT NULL,
		version INTEGER NOT NULL,
		ref_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		deleted_at TEXT,
		PRIMARY KEY(object_id, version)
	)`,
	`CREATE TABLE IF NOT EXISTS interactions (
		sequence INTEGER PRIMARY KEY AUTOINCREMENT,
		id TEXT NOT NULL UNIQUE,
		conversation_id TEXT NOT NULL REFERENCES conversations(id),
		task_id TEXT NOT NULL,
		direction TEXT NOT NULL CHECK(direction IN ('inbound', 'outbound')),
		role TEXT NOT NULL CHECK(role IN ('user', 'assistant', 'system')),
		kind TEXT NOT NULL,
		channel TEXT NOT NULL,
		content_ref_json TEXT NOT NULL,
		artifact_id TEXT,
		delivery_id TEXT,
		receipt TEXT,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS interactions_conversation_sequence ON interactions(conversation_id, sequence)`,
	`CREATE INDEX IF NOT EXISTS interactions_task ON interactions(task_id)`,
	`CREATE TABLE IF NOT EXISTS channel_messages (
		channel TEXT NOT NULL,
		external_message_id TEXT NOT NULL,
		interaction_id TEXT NOT NULL UNIQUE REFERENCES interactions(id) ON DELETE CASCADE,
		external_conversation_id TEXT NOT NULL,
		external_sender_id TEXT,
		reply_to_external_message_id TEXT,
		direction TEXT NOT NULL CHECK(direction IN ('inbound', 'outbound')),
		external_created_at TEXT NOT NULL,
		created_at TEXT NOT NULL,
		PRIMARY KEY(channel, external_message_id)
	)`,
	`CREATE INDEX IF NOT EXISTS channel_messages_conversation ON channel_messages(channel, external_conversation_id, external_created_at)`,
	`CREATE TABLE IF NOT EXISTS context_checkpoints (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		run_id TEXT NOT NULL REFERENCES runs(id),
		summary_ref_json TEXT NOT NULL,
		source_ids_json TEXT NOT NULL,
		first_kept_sequence INTEGER NOT NULL,
		summarized_count INTEGER NOT NULL,
		tokens_before INTEGER NOT NULL,
		tokens_after INTEGER NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS context_checkpoints_created ON context_checkpoints(created_at)`,
	`CREATE TABLE IF NOT EXISTS agent_checkpoints (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		run_id TEXT NOT NULL REFERENCES runs(id),
		parent_intent_id TEXT REFERENCES effect_intents(id),
		execution_id TEXT NOT NULL,
		phase TEXT NOT NULL CHECK(phase IN ('ready_for_model', 'model_received', 'candidate_received')),
		state_ref_json TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('active', 'superseded', 'completed')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS agent_checkpoints_active ON agent_checkpoints(task_id, status, updated_at)`,
	`CREATE TABLE IF NOT EXISTS attachments (
		id TEXT PRIMARY KEY,
		interaction_id TEXT NOT NULL REFERENCES interactions(id),
		name TEXT NOT NULL,
		media_type TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		content_ref_json TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS attachments_interaction ON attachments(interaction_id, created_at)`,
	`CREATE TABLE IF NOT EXISTS tasks (
		id TEXT PRIMARY KEY,
		conversation_id TEXT NOT NULL REFERENCES conversations(id),
		source_interaction_id TEXT NOT NULL,
		source_channel TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('queued', 'running', 'waiting', 'paused', 'completed', 'failed', 'canceled')),
		terminal_status TEXT NOT NULL,
		wait_reason TEXT,
		error_code TEXT,
		cancel_requested INTEGER NOT NULL DEFAULT 0 CHECK(cancel_requested IN (0, 1)),
		version INTEGER NOT NULL,
		lease_owner TEXT,
		lease_until TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS tasks_status ON tasks(status, updated_at)`,
	`CREATE TABLE IF NOT EXISTS conversation_introductions (
		conversation_id TEXT PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE,
		task_id TEXT NOT NULL UNIQUE REFERENCES tasks(id) ON DELETE CASCADE,
		requested_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS runs (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		status TEXT NOT NULL CHECK(status IN ('active', 'succeeded', 'failed', 'canceled')),
		model_status TEXT NOT NULL CHECK(model_status IN ('planned', 'dispatched', 'succeeded', 'failed', 'canceled', 'unknown')),
		soul_version TEXT NOT NULL,
		target TEXT NOT NULL,
		context_manifest_json TEXT NOT NULL,
		usage_json TEXT,
		error_code TEXT,
		started_at TEXT NOT NULL,
		updated_at TEXT NOT NULL,
		ended_at TEXT
	)`,
	`CREATE TABLE IF NOT EXISTS artifacts (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		run_id TEXT NOT NULL REFERENCES runs(id),
		version INTEGER NOT NULL,
		kind TEXT NOT NULL,
		content_ref_json TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('candidate', 'evaluated', 'approved', 'delivered', 'superseded')),
		trace_ref_json TEXT NOT NULL,
		created_at TEXT NOT NULL,
		UNIQUE(task_id, version)
	)`,
	`CREATE TABLE IF NOT EXISTS eval_records (
		id TEXT PRIMARY KEY,
		artifact_id TEXT NOT NULL REFERENCES artifacts(id),
		tier TEXT NOT NULL,
		evaluator TEXT NOT NULL,
		result TEXT NOT NULL CHECK(result IN ('pass', 'repair', 'hold', 'escalate')),
		findings_ref_json TEXT NOT NULL,
		finding_count INTEGER NOT NULL DEFAULT 0,
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS artifact_attachments (
		id TEXT PRIMARY KEY,
		artifact_id TEXT NOT NULL REFERENCES artifacts(id),
		name TEXT NOT NULL,
		media_type TEXT NOT NULL,
		size_bytes INTEGER NOT NULL,
		content_ref_json TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS artifact_attachments_artifact ON artifact_attachments(artifact_id, created_at)`,
	`CREATE TABLE IF NOT EXISTS deliveries (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		artifact_id TEXT NOT NULL REFERENCES artifacts(id),
		target_channel TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('queued', 'dispatching', 'sent', 'acknowledged', 'failed', 'unknown')),
		receipt TEXT NOT NULL,
		idempotency_key TEXT NOT NULL UNIQUE,
		terminal_status TEXT NOT NULL CHECK(terminal_status IN ('completed', 'failed')),
		continue_task INTEGER NOT NULL DEFAULT 0 CHECK(continue_task IN (0, 1)),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS effect_intents (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		run_id TEXT NOT NULL REFERENCES runs(id),
		invocation_id TEXT NOT NULL,
		tool_call_id TEXT NOT NULL,
		tool_id TEXT NOT NULL,
		tool_version TEXT NOT NULL,
		effect_class TEXT NOT NULL CHECK(effect_class IN ('read_only', 'reversible', 'communication', 'destructive', 'financial', 'privileged')),
		target TEXT NOT NULL,
		parameters_hash TEXT NOT NULL,
		payload_ref_json TEXT NOT NULL,
		parent_intent_id TEXT REFERENCES effect_intents(id),
		idempotency_key TEXT NOT NULL UNIQUE,
		control_level TEXT NOT NULL CHECK(control_level IN ('auto', 'notify_after', 'ordinary_confirm', 'strong_approval', 'deny')),
		approval_id TEXT,
		grant_id TEXT,
		reconciliation_strategy TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('planned', 'authorized', 'dispatched', 'confirmed', 'failed', 'unknown', 'compensated')),
		result_ref_json TEXT,
		error_code TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS effect_intents_task ON effect_intents(task_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS effect_intents_recovery ON effect_intents(status, updated_at)`,
	`CREATE INDEX IF NOT EXISTS effect_intents_parent ON effect_intents(parent_intent_id, created_at)`,
	`CREATE TABLE IF NOT EXISTS subagent_runs (
		id TEXT PRIMARY KEY REFERENCES effect_intents(id),
		role_id TEXT NOT NULL,
		provider_id TEXT NOT NULL,
		parent_task_id TEXT NOT NULL REFERENCES tasks(id),
		parent_run_id TEXT NOT NULL REFERENCES runs(id),
		access_mode TEXT NOT NULL CHECK(access_mode IN ('read_only', 'workspace_write')),
		status TEXT NOT NULL CHECK(status IN ('queued', 'starting', 'running', 'completed', 'failed', 'unknown', 'canceled')),
		request_ref_json TEXT NOT NULL,
		result_ref_json TEXT,
		runtime_state_ref_json TEXT,
		continuation_ref_json TEXT,
		progress_delivery_id TEXT REFERENCES deliveries(id) DEFERRABLE INITIALLY DEFERRED,
		runtime_id TEXT,
		error_code TEXT,
		started_at TEXT,
		completed_at TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS subagent_runs_active_task
		ON subagent_runs(parent_task_id)
		WHERE status IN ('queued', 'starting', 'running')`,
	`CREATE INDEX IF NOT EXISTS subagent_runs_status ON subagent_runs(status, updated_at)`,
	`CREATE TABLE IF NOT EXISTS memory_claims (
		id TEXT PRIMARY KEY,
		statement_key TEXT NOT NULL UNIQUE,
		statement_ref_json TEXT NOT NULL,
		kind TEXT NOT NULL,
		scope TEXT NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS memory_evidence (
		id TEXT PRIMARY KEY,
		claim_id TEXT NOT NULL REFERENCES memory_claims(id),
		evidence_key TEXT NOT NULL UNIQUE,
		evidence_ref_json TEXT NOT NULL,
		relation TEXT NOT NULL CHECK(relation IN ('supports', 'contradicts', 'qualifies')),
		source_type TEXT NOT NULL,
		source_ref TEXT NOT NULL,
		independence_group TEXT NOT NULL,
		reliability REAL NOT NULL,
		directness REAL NOT NULL,
		verifiability REAL NOT NULL,
		observed_at TEXT NOT NULL,
		valid_until TEXT,
		status TEXT NOT NULL CHECK(status IN ('active', 'withdrawn', 'deleted')),
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS memory_evidence_claim ON memory_evidence(claim_id, status, observed_at)`,
	`CREATE TABLE IF NOT EXISTS memory_beliefs (
		claim_id TEXT PRIMARY KEY REFERENCES memory_claims(id),
		status TEXT NOT NULL CHECK(status IN ('supported', 'tentative', 'contested', 'unlikely', 'unknown')),
		confidence REAL NOT NULL,
		support_weight REAL NOT NULL,
		contradict_weight REAL NOT NULL,
		independent_groups INTEGER NOT NULL,
		expired INTEGER NOT NULL DEFAULT 0 CHECK(expired IN (0, 1)),
		version INTEGER NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS memory_items (
		id TEXT PRIMARY KEY,
		claim_id TEXT NOT NULL UNIQUE REFERENCES memory_claims(id),
		kind TEXT NOT NULL,
		scope TEXT NOT NULL,
		salience REAL NOT NULL,
		access_count INTEGER NOT NULL DEFAULT 0,
		last_accessed_at TEXT,
		last_consolidated_at TEXT,
		pinned INTEGER NOT NULL DEFAULT 0 CHECK(pinned IN (0, 1)),
		status TEXT NOT NULL CHECK(status IN ('candidate', 'active', 'low_salience', 'archived', 'deleted')),
		usage_policy TEXT NOT NULL CHECK(usage_policy IN ('allow', 'do_not_use')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS memory_items_retrieval ON memory_items(status, usage_policy, updated_at)`,
	`CREATE TABLE IF NOT EXISTS memory_terms (
		memory_id TEXT NOT NULL REFERENCES memory_items(id),
		term_key TEXT NOT NULL,
		PRIMARY KEY(memory_id, term_key)
	)`,
	`CREATE INDEX IF NOT EXISTS memory_terms_lookup ON memory_terms(term_key, memory_id)`,
	`CREATE TABLE IF NOT EXISTS memory_semantic_index (
		memory_id TEXT PRIMARY KEY REFERENCES memory_items(id),
		model_id TEXT NOT NULL,
		dimensions INTEGER NOT NULL,
		content_hash TEXT NOT NULL,
		vector_ref_json TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS memory_semantic_index_model ON memory_semantic_index(model_id, updated_at)`,
	`CREATE TABLE IF NOT EXISTS memory_associations (
		left_memory_id TEXT NOT NULL REFERENCES memory_items(id),
		right_memory_id TEXT NOT NULL REFERENCES memory_items(id),
		weight REAL NOT NULL,
		last_reinforced_at TEXT NOT NULL,
		PRIMARY KEY(left_memory_id, right_memory_id),
		CHECK(left_memory_id < right_memory_id)
	)`,
	`CREATE INDEX IF NOT EXISTS memory_associations_right ON memory_associations(right_memory_id, weight)`,
	`CREATE TABLE IF NOT EXISTS memory_retrievals (
		id TEXT PRIMARY KEY,
		run_id TEXT NOT NULL REFERENCES runs(id),
		source_interaction_id TEXT NOT NULL REFERENCES interactions(id),
		query_key TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS memory_retrieval_items (
		retrieval_id TEXT NOT NULL REFERENCES memory_retrievals(id),
		memory_id TEXT NOT NULL REFERENCES memory_items(id),
		rank INTEGER NOT NULL,
		score REAL NOT NULL,
		reasons_json TEXT NOT NULL,
		injected INTEGER NOT NULL CHECK(injected IN (0, 1)),
		used INTEGER NOT NULL DEFAULT 0 CHECK(used IN (0, 1)),
		used_at TEXT,
		PRIMARY KEY(retrieval_id, memory_id)
	)`,
	`CREATE INDEX IF NOT EXISTS memory_retrieval_items_memory ON memory_retrieval_items(memory_id, used, rank)`,
	`CREATE TABLE IF NOT EXISTS memory_delete_jobs (
		memory_id TEXT PRIMARY KEY,
		claim_id TEXT NOT NULL,
		refs_json TEXT NOT NULL,
		affected_json TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('pending', 'completed')),
		created_at TEXT NOT NULL,
		completed_at TEXT
	)`,
	`CREATE TABLE IF NOT EXISTS commitments (
		id TEXT PRIMARY KEY,
		message_ref_json TEXT NOT NULL,
		schedule_json TEXT NOT NULL,
		importance TEXT NOT NULL CHECK(importance IN ('normal', 'important')),
		status TEXT NOT NULL CHECK(status IN ('active', 'paused', 'completed', 'canceled')),
		next_run_at TEXT,
		last_run_at TEXT,
		version INTEGER NOT NULL,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS commitments_due ON commitments(status, next_run_at)`,
	`CREATE TABLE IF NOT EXISTS commitment_fires (
		commitment_id TEXT NOT NULL REFERENCES commitments(id),
		scheduled_for TEXT NOT NULL,
		task_id TEXT NOT NULL UNIQUE,
		target_channel TEXT NOT NULL,
		target_conversation_id TEXT NOT NULL,
		reply_to_message_id TEXT NOT NULL,
		routing_mode TEXT NOT NULL CHECK(routing_mode IN ('origin_channel', 'recent_channel')),
		created_at TEXT NOT NULL,
		PRIMARY KEY(commitment_id, scheduled_for)
	)`,
	`CREATE TABLE IF NOT EXISTS model_budget_usage (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		estimated_tokens INTEGER NOT NULL,
		actual_tokens INTEGER,
		charged_tokens INTEGER NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('reserved', 'settled', 'unknown')),
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS model_budget_usage_task ON model_budget_usage(task_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS model_budget_usage_time ON model_budget_usage(created_at, status)`,
	`CREATE TABLE IF NOT EXISTS episodes (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL UNIQUE REFERENCES tasks(id),
		manifest_ref_json TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('ready', 'invalidated', 'deleted')),
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS dataset_candidates (
		id TEXT PRIMARY KEY,
		episode_id TEXT NOT NULL UNIQUE REFERENCES episodes(id),
		status TEXT NOT NULL CHECK(status IN ('candidate', 'rejected', 'invalidated')),
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS dataset_snapshots (
		id TEXT PRIMARY KEY,
		version INTEGER NOT NULL UNIQUE,
		purpose TEXT NOT NULL,
		manifest_ref_json TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('frozen', 'invalidated')),
		item_count INTEGER NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS dataset_snapshot_items (
		snapshot_id TEXT NOT NULL REFERENCES dataset_snapshots(id),
		candidate_id TEXT NOT NULL REFERENCES dataset_candidates(id),
		episode_id TEXT NOT NULL REFERENCES episodes(id),
		task_id TEXT NOT NULL REFERENCES tasks(id),
		split TEXT NOT NULL CHECK(split IN ('development', 'eval', 'holdout')),
		PRIMARY KEY(snapshot_id, candidate_id)
	)`,
	`CREATE INDEX IF NOT EXISTS dataset_snapshot_items_task ON dataset_snapshot_items(task_id, snapshot_id)`,
	`CREATE TABLE IF NOT EXISTS feedback_records (
		id TEXT PRIMARY KEY,
		feedback_task_id TEXT NOT NULL REFERENCES tasks(id),
		source_task_id TEXT NOT NULL REFERENCES tasks(id),
		artifact_id TEXT NOT NULL REFERENCES artifacts(id),
		delivery_id TEXT NOT NULL REFERENCES deliveries(id),
		kind TEXT NOT NULL CHECK(kind IN ('correction', 'accepted', 'rejected', 'outcome')),
		outcome TEXT NOT NULL CHECK(outcome IN ('', 'success', 'failure', 'mixed', 'unknown')),
		statement_ref_json TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS feedback_records_source ON feedback_records(source_task_id, created_at)`,
	`CREATE INDEX IF NOT EXISTS feedback_records_task ON feedback_records(feedback_task_id, created_at)`,
	`CREATE TABLE IF NOT EXISTS evolution_releases (
		id TEXT PRIMARY KEY,
		version INTEGER NOT NULL UNIQUE,
		status TEXT NOT NULL CHECK(status IN ('canary', 'active', 'retired')),
		experience_ref_json TEXT NOT NULL,
		offline_review_ref_json TEXT NOT NULL,
		source_key TEXT NOT NULL UNIQUE,
		training_signal_count INTEGER NOT NULL,
		holdout_signal_count INTEGER NOT NULL,
		offline_score REAL NOT NULL,
		baseline_score REAL NOT NULL,
		pass_count INTEGER NOT NULL DEFAULT 0,
		fail_count INTEGER NOT NULL DEFAULT 0,
		created_at TEXT NOT NULL,
		activated_at TEXT,
		retired_at TEXT
	)`,
	`CREATE UNIQUE INDEX IF NOT EXISTS evolution_one_canary ON evolution_releases(status) WHERE status = 'canary'`,
	`CREATE UNIQUE INDEX IF NOT EXISTS evolution_one_active ON evolution_releases(status) WHERE status = 'active'`,
	`CREATE TABLE IF NOT EXISTS evolution_signals (
		id TEXT PRIMARY KEY,
		run_id TEXT NOT NULL REFERENCES runs(id),
		release_id TEXT NOT NULL DEFAULT '',
		result TEXT NOT NULL CHECK(result IN ('pass', 'repair', 'hold', 'escalate')),
		tier TEXT NOT NULL,
		findings_ref_json TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS evolution_signals_recent ON evolution_signals(created_at DESC)`,
	`CREATE TABLE IF NOT EXISTS approvals (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL REFERENCES tasks(id),
		effect_intent_id TEXT NOT NULL REFERENCES effect_intents(id),
		control_level TEXT NOT NULL CHECK(control_level IN ('ordinary_confirm', 'strong_approval')),
		target TEXT NOT NULL,
		parameters_hash TEXT NOT NULL,
		continuation_ref_json TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'denied', 'expired', 'revoked')),
		expires_at TEXT NOT NULL,
		decided_at TEXT,
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS capability_grants (
		id TEXT PRIMARY KEY,
		approval_id TEXT NOT NULL REFERENCES approvals(id),
		task_id TEXT NOT NULL REFERENCES tasks(id),
		tool_id TEXT NOT NULL,
		tool_version TEXT NOT NULL,
		effect_class TEXT NOT NULL,
		target TEXT NOT NULL,
		parameters_hash TEXT NOT NULL,
		control_level TEXT NOT NULL,
		expires_at TEXT NOT NULL,
		max_uses INTEGER NOT NULL,
		uses INTEGER NOT NULL,
		revoked_at TEXT,
		created_at TEXT NOT NULL
	)`,
	`CREATE TABLE IF NOT EXISTS events (
		sequence INTEGER PRIMARY KEY AUTOINCREMENT,
		id TEXT NOT NULL UNIQUE,
		aggregate_type TEXT NOT NULL,
		aggregate_id TEXT NOT NULL,
		type TEXT NOT NULL,
		payload_json TEXT NOT NULL,
		created_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS events_aggregate ON events(aggregate_type, aggregate_id, sequence)`,
	`CREATE TABLE IF NOT EXISTS internal_outbox (
		id TEXT PRIMARY KEY,
		kind TEXT NOT NULL,
		aggregate_id TEXT NOT NULL,
		status TEXT NOT NULL CHECK(status IN ('pending', 'processing', 'done')),
		attempts INTEGER NOT NULL,
		available_at TEXT NOT NULL,
		lease_owner TEXT,
		lease_until TEXT,
		last_error TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS internal_outbox_ready ON internal_outbox(status, available_at, created_at)`,
	`CREATE TABLE IF NOT EXISTS data_erasure_jobs (
		id TEXT PRIMARY KEY,
		task_id TEXT NOT NULL UNIQUE,
		status TEXT NOT NULL CHECK(status IN ('awaiting_delivery', 'ready', 'completed')),
		content_objects INTEGER NOT NULL DEFAULT 0,
		completed_at TEXT,
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL
	)`,
	`CREATE INDEX IF NOT EXISTS data_erasure_jobs_status ON data_erasure_jobs(status, created_at)`,
}
